model/RdsResultStorage.php

Single query to insert variables

---

manifest.php
scripts/update/Updater.php

increase version number

---

manifest.php
scripts/install/setDefault.php
scripts/update/Updater.php

Release 3.4.0

---

manifest.php
model/RdsResultStorage.php
scripts/update/Updater.php

Depends:
https://github.com/oat-sa/extension-tao-outcome/pull/109

Feature/tao 5824/delete delivery

---

composer.json
manifest.php
model/RdsResultStorage.php
scripts/update/Updater.php

Delivery execution deletion support

Release 4.0.1

---

manifest.php
model/RdsResultStorage.php
scripts/update/Updater.php

Depends on https://github.com/oat-sa/extension-tao-outcome/pull/116

Feature/tao 5954/optimise result page

---

composer.json
manifest.php
scripts/update/Updater.php

Release 4.2.2

---

manifest.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

According to https://oat-sa.atlassian.net/browse/TAO-6469

Tao 6469 fix backend tests

---

manifest.php
model/RdsResultStorage.php
scripts/update/Updater.php

Release 4.3.0

---

manifest.php
model/RdsResultStorage.php
scripts/install/createTables.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

Depends on https://github.com/oat-sa/generis/pull/529

Fix/tao 6892/fix tests tao outcome rds extension

---

locales/en-US/messages.lang.php
manifest.php
model/RdsResultStorage.php
scripts/install/createTables.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

Release 5.0.1

---

manifest.php
scripts/install/AddIndexes.php
scripts/uninstall/removeTables.php
scripts/update/Updater.php

Release 6.0.0

---

manifest.php
model/RdsResultStorage.php
scripts/update/Updater.php

Related PR: https://github.com/oat-sa/extension-tao-outcomerds/pull/89
Changed the double quotes to queryBuilder parameter to ensure it works properly with all DB drivers.

Fix/nex 168/postgres compatibility issue

---

manifest.php
model/RdsResultStorage.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

Release 6.0.2

---

manifest.php
model/RdsResultStorage.php
scripts/install/createTables.php
scripts/update/Updater.php
scripts/update/dbMigrations/v6_1_0/VariablesStorage_v1.php
test/unit/model/RdsResultStorageTest.php

Release 6.1.0

---

README.md
manifest.php
scripts/update/Updater.php

Related to: https://oat-sa.atlassian.net/browse/TAO-8970
Added the configuration documentation for tao-outcome: see the readme.md.

Feature/tao 8970/config options documented

---

README.md
manifest.php
scripts/update/Updater.php

Release 6.3.0

---

config/default/RdsResultStorage.conf.php
manifest.php
model/AbstractRdsResultStorage.php
model/NewSqlResultStorage.php
model/RdsResultStorage.php
scripts/bench/AbstractStoreItemVariable.php
scripts/bench/StoreItemVariable.php
scripts/bench/StoreItemVariables.php
scripts/install/AddIndexes.php
scripts/install/CreateTables.php
scripts/install/setDefault.php
scripts/test.php
scripts/tools/KvToRdsMigration.php
scripts/uninstall/removeTables.php
scripts/update/Updater.php
scripts/update/dbMigrations/v6_1_0/VariablesStorage_v1.php
test/unit/model/NewSqlResultStorageTest.php
test/unit/model/RdsResultStorageTest.php

Release 6.3.1

---

manifest.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8

Feature/tdr 1/phpunit8 upgrade

---

manifest.php
model/AbstractRdsResultStorage.php
model/NewSqlResultStorage.php
scripts/update/Updater.php
test/unit/model/NewSqlResultStorageTest.php
test/unit/model/RdsResultStorageTest.php

Release 6.4.1

---

manifest.php
model/AbstractRdsResultStorage.php
scripts/tools/KvToRdsMigration.php
scripts/update/Updater.php

Release 7.0.0

---

.Jenkinsfile
manifest.php
scripts/update/Updater.php

Release 7.2.1

---

.gitignore
manifest.php
scripts/update/Updater.php

Release 7.3.1

---

composer.json
manifest.php

Release 8.0.0

---

.github/workflows/continous-integration.yml
.github/workflows/release.yml

Release 8.0.1

---

.github/workflows/continuous-integration.yaml
README.md
composer.json

This PR aims to integrate the extension with a new CI pipeline defined by https://github.com/oat-sa/tao-extension-ci-action
⚠️ It is expected that PHP > 7.4 pipeline fail ⚠️
- ci: add a CI action
- docs: add a codecov badge to README.md

Feature ADF-1102 CI pipeline

---

.github/workflows/continuous-integration.yaml
README.md
composer.json

Release 8.2.1

---

.github/workflows/continuous-integration.yaml
composer.json

Release 8.2.2

---

composer.json
model/AbstractRdsResultStorage.php
test/unit/model/AbstractRdsResultStorageTest.php

Release 8.3.0

---

model/NewSqlResultStorage.php
model/RdsResultStorage.php
scripts/bench/AbstractStoreItemVariable.php
scripts/bench/StoreItemVariable.php
scripts/bench/StoreItemVariables.php
scripts/install/AddIndexes.php
scripts/test.php
scripts/tools/KvToRdsMigration.php
scripts/uninstall/removeTables.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

[ADF-1440]: https://oat-sa.atlassian.net/browse/ADF-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: apply PSR-12

---

model/NewSqlResultStorage.php
model/RdsResultStorage.php
scripts/bench/AbstractStoreItemVariable.php
scripts/bench/StoreItemVariable.php
scripts/bench/StoreItemVariables.php
scripts/install/AddIndexes.php
scripts/test.php
scripts/tools/KvToRdsMigration.php
scripts/uninstall/removeTables.php
scripts/update/Updater.php
test/unit/model/RdsResultStorageTest.php

Release 8.3.1
